"""
Install / remove the C2UI agent hook in the SFM installation.

Two entry points are written (both safe to delete, both idempotent):

1. game/usermod/scripts/sfm/sfm_init.py   - auto-start on SFM launch (a marked block
   is appended; the original content is preserved and backed up once as *.c2ui.bak).
2. game/usermod/scripts/sfm/mainmenu/C2UI/Start_C2UI_Agent.py - manual start from
   SFM's *Scripts* menu (useful if the init hook is disabled).

Run as a script:  python install_agent.py [--uninstall] [--status]
"""
from __future__ import annotations

import argparse
import logging
import shutil
import sys
from pathlib import Path
from typing import Dict, Optional

log = logging.getLogger("c2ui.install")

_HERE = Path(__file__).resolve().parent
_SDK_ROOT = _HERE.parents[2]
if str(_SDK_ROOT) not in sys.path:
    sys.path.insert(0, str(_SDK_ROOT))

from Core.Library import paths  # noqa: E402

MARK_BEGIN = "# >>> C2UI agent hook (auto-generated by C2UI_SDK - safe to remove) >>>"
MARK_END = "# <<< C2UI agent hook <<<"

HOOK_TEMPLATE = """{begin}
try:
    import os as _c2ui_os, sys as _c2ui_sys
    _c2ui_dir = {agent_dir!r}
    if _c2ui_os.environ.get("C2UI_DISABLE_AGENT", "") != "1" and _c2ui_os.path.isdir(_c2ui_dir):
        if _c2ui_dir not in _c2ui_sys.path:
            _c2ui_sys.path.insert(0, _c2ui_dir)
        import c2ui_agent as _c2ui_agent
        _c2ui_agent.start()
except Exception:
    import traceback as _c2ui_tb
    _c2ui_tb.print_exc()
{end}
"""

MENU_SCRIPT = '''# C2UI: start the agent manually (Scripts menu > C2UI > Start C2UI Agent)
import os, sys
_c2ui_dir = {agent_dir!r}
if _c2ui_dir not in sys.path:
    sys.path.insert(0, _c2ui_dir)
import c2ui_agent
_agent = c2ui_agent.start()
print("C2UI agent: %s" % ("running on port %d" % _agent.port if _agent else "failed to start"))
'''

DEFAULT_INIT = "# Initial Script after SFM started up, and the main window got focus\n\nprint \"USERMOD: Python initial startup complete\"\n"


class SFMNotFound(RuntimeError):
    """Raised when the agent hook cannot be written because SFM is not configured."""


def _scripts_dir() -> Path:
    d = paths.sfm_usermod_scripts_dir()
    if d is None:
        raise SFMNotFound("SFM installation is not configured - set the SFM path in Preferences")
    return d


def init_file() -> Optional[Path]:
    d = paths.sfm_usermod_scripts_dir()
    return d / "sfm_init.py" if d else None


def menu_script_file() -> Optional[Path]:
    d = paths.sfm_usermod_scripts_dir()
    return d / "mainmenu" / "C2UI" / "Start_C2UI_Agent.py" if d else None


def agent_dir() -> str:
    return str(_HERE)


def is_installed() -> bool:
    f = init_file()
    if f is None or not f.is_file():
        return False
    try:
        return MARK_BEGIN in f.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False


def _strip_hook(text: str) -> str:
    while MARK_BEGIN in text and MARK_END in text:
        a = text.index(MARK_BEGIN)
        b = text.index(MARK_END, a) + len(MARK_END)
        text = text[:a].rstrip("\n") + "\n" + text[b:].lstrip("\n")
    return text


def install() -> Dict[str, str]:
    f = _scripts_dir() / "sfm_init.py"
    f.parent.mkdir(parents=True, exist_ok=True)
    if f.is_file():
        original = f.read_text(encoding="utf-8", errors="replace")
        bak = f.with_suffix(".py.c2ui.bak")
        if not bak.exists():
            shutil.copy2(f, bak)
    else:
        original = DEFAULT_INIT
    hook = HOOK_TEMPLATE.format(begin=MARK_BEGIN, end=MARK_END, agent_dir=agent_dir())
    new_text = _strip_hook(original).rstrip("\n") + "\n\n" + hook
    f.write_text(new_text, encoding="utf-8")

    m = _scripts_dir() / "mainmenu" / "C2UI" / "Start_C2UI_Agent.py"
    m.parent.mkdir(parents=True, exist_ok=True)
    m.write_text(MENU_SCRIPT.format(agent_dir=agent_dir()), encoding="utf-8")
    log.info("C2UI agent hook installed: %s", f)
    return {"init": str(f), "menu_script": str(m)}


def uninstall() -> Dict[str, str]:
    f = init_file()
    if f is None:
        raise SFMNotFound("SFM installation is not configured")
    if f.is_file():
        f.write_text(_strip_hook(f.read_text(encoding="utf-8", errors="replace")), encoding="utf-8")
    m = menu_script_file()
    if m is not None and m.is_file():
        m.unlink()
        try:
            m.parent.rmdir()
        except OSError:
            pass
    log.info("C2UI agent hook removed from %s", f)
    return {"init": str(f)}


def status() -> Dict[str, object]:
    menu = menu_script_file()
    init = init_file()
    return {
        "sfm_root": str(paths.sfm_root() or "(not configured)"),
        "sfm_found": paths.sfm_is_installed(),
        "init_file": str(init) if init else "(unavailable)",
        "installed": is_installed(),
        "menu_script": bool(menu and menu.is_file()),
        "agent_dir": agent_dir(),
    }


def main(argv=None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    p = argparse.ArgumentParser(description="Install the C2UI agent hook into SFM")
    p.add_argument("--uninstall", action="store_true")
    p.add_argument("--status", action="store_true")
    p.add_argument("--path", help="SFM installation folder (the one containing game/sfm.exe)")
    ns = p.parse_args(argv)
    if ns.status:
        for k, v in status().items():
            print(f"{k}: {v}")
        return 0
    if ns.path:
        ok, res = paths.set_sfm_root(ns.path)
        if not ok:
            print(f"invalid SFM path: {res}")
            return 1
    if not paths.sfm_is_installed():
        print("SFM not found. Pass --path <SourceFilmmaker folder> or set C2UI_SFM_ROOT.")
        return 1
    try:
        result = uninstall() if ns.uninstall else install()
    except SFMNotFound as exc:
        print(exc)
        return 1
    for k, v in result.items():
        print(f"{k}: {v}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
